/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WebcamLib */

#ifndef _Included_WebcamLib
#define _Included_WebcamLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WebcamLib
 * Method:    videoRutine
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_WebcamLib_videoRutine
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
